# -*- coding: utf-8 -*-
"""Amazon ML Challenge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17sTrnD_y_XiNdB3SRvrz8PAGWiT9uKvw
"""

from google.colab import drive
drive.mount('/content/drive')

source1 = '/content/drive/MyDrive/Amazon ML Challenge/student_resource/dataset/train/train_source1.tsv'
source2 = '/content/drive/MyDrive/Amazon ML Challenge/student_resource/dataset/train/train_source2.tsv'
source3 = '/content/drive/MyDrive/Amazon ML Challenge/student_resource/dataset/train/train_source3.tsv'
gt = '/content/drive/MyDrive/Amazon ML Challenge/student_resource/dataset/train/train_ground_truth.tsv'
test1 = '/content/drive/MyDrive/Amazon ML Challenge/student_resource/dataset/test/test_source1.tsv'
test2 = '/content/drive/MyDrive/Amazon ML Challenge/student_resource/dataset/test/test_source2.tsv'
test3 = '/content/drive/MyDrive/Amazon ML Challenge/student_resource/dataset/test/test_source3.tsv'

def load_source_tsv(path: str) -> pd.DataFrame:
    """
    Load a source file with the exact dtype/NA handling entity resolution
    needs: keep empty strings as empty strings (not NaN) so every .str
    method downstream is safe, but track true missingness explicitly first.
    """
    df = pd.read_csv(path, sep="\t", dtype=str, keep_default_na=False)
    for col in ("business_name", "business_address"):
        if col in df.columns:
            df[f"{col}_missing"] = df[col].isna() | (df[col].str.strip() == "")
            df[col] = df[col].fillna("")
    return df

import pandas as pd
import re

try:
    # Using 'source1' variable as defined in t-E85tSOvR3P
    df = load_source_tsv(source1)
    print(f"Successfully loaded data from '{source1}'. First 5 rows:")
    display(df.head())
except FileNotFoundError:
    print(f"Error: The file at '{source1}' was not found. Please check the path.")
except Exception as e:
    print(f"An error occurred while loading the TSV: {e}")

try:
    df2 = load_source_tsv(source2)
    print(f"Successfully loaded data from '{source2}'. First 5 rows:")
    display(df2.head())
except FileNotFoundError:
    print(f"Error: The file at '{source2}' was not found. Please check the path.")
except Exception as e:
    print(f"An error occurred while loading the TSV: {e}")

try:
    df3 = load_source_tsv(source3)
    print(f"Successfully loaded data from '{source3}'. First 5 rows:")
    display(df3.head())
except FileNotFoundError:
    print(f"Error: The file at '{source3}' was not found. Please check the path.")
except Exception as e:
    print(f"An error occurred while loading the TSV: {e}")

print("Checking for missing 'business_name' or 'business_address' in df2:")
missing_fields_df2 = df2[df2['business_name'].isna() | df2['business_address'].isna()]

if not missing_fields_df2.empty:
    print(f"Found {len(missing_fields_df2)} rows in df2 with missing 'business_name' or 'business_address':")
    display(missing_fields_df2.head())
else:
    print("No rows in df2 have missing 'business_name' or 'business_address'.")

try:
    # Load the ground truth file
    df_gt = pd.read_csv(gt, sep='\t')
    print(f"Successfully loaded the ground truth file from '{gt}'. First 5 rows:")
    display(df_gt.head())
except FileNotFoundError:
    print(f"Error: The ground truth file at '{gt}' was not found. Please check the path.")
except Exception as e:
    print(f"An error occurred while loading the ground truth TSV: {e}")

from __future__ import annotations

import unicodedata
from collections import Counter
from dataclasses import dataclass, field
from typing import Optional

!pip install indic-transliteration jellyfish

try:
    from indic_transliteration import sanscript
    _HAS_INDIC = True
except ImportError:
    _HAS_INDIC = False

try:
    import jellyfish
    _HAS_JELLYFISH = True
except ImportError:
    _HAS_JELLYFISH = False

_URL_RE = re.compile(
    r"(?:https?://)?(?:www\.)?([a-z0-9][a-z0-9\-]*\.[a-z]{2,}(?:\.[a-z]{2,})?)",
    re.IGNORECASE,
)
_EMAIL_RE = re.compile(r"[\w.+-]+@([\w-]+\.[\w.-]+)")


def extract_domain(text: str) -> Optional[str]:
    """
    Pull an embedded website/email domain out of a name or address field.
    This is one of the strongest available match signals in this dataset
    (e.g. 'SHIVSHAKTI VIDYALAYA ... | www.shivshakti.com', or a bare
    'heassociates.com' used as the entire name) — a shared domain across
    two records from different sources is near-deterministic evidence of
    the same entity, stronger than any string-similarity score.
    """
    if not text:
        return None
    m = _EMAIL_RE.search(text)
    if m:
        return m.group(1).lower().rstrip(".")
    m = _URL_RE.search(text)
    if m:
        domain = m.group(1).lower().rstrip(".")
        # avoid false positives like "Inc." or decimal-looking tokens
        if "." in domain and not domain.replace(".", "").isdigit():
            return domain
    return None


def has_repeated_token(text: str) -> bool:
    """
    Flags scraping/concatenation artifacts like 'Delta Tetlecommunication
    Inc Inc' or 'Keystone Odyssey Odyssey LLC'. We don't silently dedupe at
    the string level (would corrupt legitimately repeated words), but this
    flag + a deduped variant (see dedupe_repeated_tokens) let similarity
    features avoid being depressed by pure noise.
    """
    tokens = text.lower().split()
    if len(tokens) < 2:
        return False
    counts = Counter(tokens)
    return any(c > 1 for tok, c in counts.items() if len(tok) > 2)


def dedupe_repeated_tokens(text: str) -> str:
    """Collapse immediate consecutive duplicate tokens only (safe, local)."""
    tokens = text.split()
    out = []
    for tok in tokens:
        if not out or out[-1].lower() != tok.lower():
            out.append(tok)
    return " ".join(out)


_NUMERIC_TOKEN_RE = re.compile(r"\b\d[\d/\-]*\b")


def extract_numeric_tokens(address: str) -> list[str]:
    """
    Pull building numbers, unit numbers, PIN/ZIP codes etc. as an unordered
    set. Numeric overlap between two addresses is a cheap, high-precision
    blocking signal independent of edit-distance on the full messy string.
    """
    if not address:
        return []
    return _NUMERIC_TOKEN_RE.findall(address)

_SCRIPT_RANGES = {
    "devanagari": (0x0900, 0x097F),
    "tamil": (0x0B80, 0x0BFF),
    "bengali": (0x0980, 0x09FF),
    "telugu": (0x0C00, 0x0C7F),
    "kannada": (0x0C80, 0x0CFF),
    "malayalam": (0x0D00, 0x0D7F),
    "gujarati": (0x0A80, 0x0AFF),
    "gurmukhi": (0x0A00, 0x0A7F),
}


def detect_script(text: str) -> str:
    """
    Cheap, dependency-free Unicode-block detection. Returns the dominant
    non-Latin script if present, else 'latin', else 'unknown' for empty text.
    Must run BEFORE normalization: casefold/NFKC is safe for any script, but
    which transliteration scheme and which suffix-dictionary to apply is
    decided from this result.
    """
    if not text or not text.strip():
        return "unknown"
    counts = Counter()
    for ch in text:
        cp = ord(ch)
        if cp < 128:
            if ch.isalpha():
                counts["latin"] += 1
            continue
        for name, (lo, hi) in _SCRIPT_RANGES.items():
            if lo <= cp <= hi:
                counts[name] += 1
                break
    if not counts:
        return "unknown"
    dominant, dom_count = counts.most_common(1)[0]
    total = sum(counts.values())
    # mixed if no script has a clear majority (e.g. name + embedded domain)
    if dom_count / total < 0.6 and len(counts) > 1:
        return "mixed"
    return dominant

_WHITESPACE_RE = re.compile(r"\s+")
_PUNCT_KEEP_ALNUM_RE = re.compile(r"[^\w\s&/-]", re.UNICODE)


def _unicode_normalize(text: str) -> str:
    return unicodedata.normalize("NFKC", text)


def _casefold(text: str) -> str:
    return text.casefold()


def _normalize_whitespace(text: str) -> str:
    return _WHITESPACE_RE.sub(" ", text).strip()


def _normalize_punctuation(text: str) -> str:
    text = text.replace("&", " and ")
    text = _PUNCT_KEEP_ALNUM_RE.sub(" ", text)
    return _normalize_whitespace(text)


_SEED_SUFFIX_MAP = {
    # US
    "incorporated": "inc", "inc": "inc",
    "corporation": "corp", "corp": "corp",
    "company": "co", "co": "co",
    "limited liability company": "llc", "llc": "llc",
    "limited liability partnership": "llp", "llp": "llp",
    "limited partnership": "lp", "lp": "lp",
    # India
    "private limited": "pvt ltd", "pvt limited": "pvt ltd",
    "private ltd": "pvt ltd", "pvt ltd": "pvt ltd",
    "limited": "ltd", "ltd": "ltd",
    "private": "pvt", "pvt": "pvt",
    # France (present only in test — included so the pipeline doesn't need
    # to be touched when test data arrives; harmless no-op on train)
    "societe a responsabilite limitee": "sarl", "sarl": "sarl",
    "societe anonyme": "sa", "sa": "sa",
    "societe par actions simplifiee": "sas", "sas": "sas",
}


def build_suffix_map(train_name_series: pd.Series,
                      extra_map: Optional[dict] = None) -> dict:
    """
    Extend _SEED_SUFFIX_MAP by frequency-mining trailing tokens from the
    actual training corpus. This keeps normalization from being blind to
    suffix variants that exist in the data but weren't anticipated by hand.
    Run this once per project, inspect the discovered candidates, and pass
    a vetted `extra_map` back in — this function surfaces candidates, it
    does not auto-apply anything you haven't reviewed.
    """
    suffix_map = dict(_SEED_SUFFIX_MAP)
    if extra_map:
        suffix_map.update(extra_map)
    return suffix_map


def _normalize_suffix(text: str, suffix_map: dict) -> str:
    tokens = text.split()
    if not tokens:
        return text
    # try 3-word, then 2-word, then 1-word trailing suffix matches
    for n in (3, 2, 1):
        if len(tokens) >= n:
            tail = " ".join(tokens[-n:])
            if tail in suffix_map:
                tokens = tokens[:-n] + [suffix_map[tail]]
                break
    return " ".join(tokens)

_SUFFIX_TOKENS = set(_SEED_SUFFIX_MAP.values())  # {"inc","corp","co","llc","llp","lp","pvt ltd","ltd","pvt","sarl","sa","sas"}

def strip_suffix(normalized_name: str) -> str:
    """Removes a trailing canonical suffix entirely, for matching cases
    where only one side of a pair includes the legal suffix."""
    tokens = normalized_name.split()
    for n in (2, 1):
        if len(tokens) > n and " ".join(tokens[-n:]) in _SUFFIX_TOKENS:
            return " ".join(tokens[:-n])
    return normalized_name

def normalize_name(raw_name: str, suffix_map: dict, script: str = "latin") -> tuple[str, str]:
    """
    Returns (normalized_name, name_without_domain). Domain must already have
    been extracted (Stage 1) by the caller and stripped here so it doesn't
    pollute string-similarity features.

    For non-Latin scripts, suffix normalization and punctuation stripping
    are skipped: the Latin-alphabet suffix map (pvt/ltd/...) doesn't apply
    to Devanagari/Tamil/etc. text, and our punctuation regex is tuned for
    Latin scripts. Non-Latin names get Unicode-normalized + whitespace-
    cleaned only; suffix/domain-style normalization happens later on the
    transliterated form instead (Stage 4), where it IS Latin text.
    """
    text = raw_name
    text = _URL_RE.sub(" ", _EMAIL_RE.sub(" ", text))
    text = _unicode_normalize(text)

    if script == "latin":
        text = _casefold(text)
        text = _normalize_punctuation(text)
        text = _normalize_suffix(text, suffix_map)
        text = _normalize_whitespace(text)
    else:
        # light-touch: just collapse whitespace, preserve the script as-is
        text = _normalize_whitespace(text)

    return text, text


_ADDRESS_ABBREV_MAP = {
    "rd": "road", "st": "street", "ave": "avenue", "dr": "drive",
    "ln": "lane", "blvd": "boulevard", "hwy": "highway", "ct": "court",
    "apt": "apartment", "bldg": "building", "flr": "floor", "fl": "floor",
    "no": "number", "opp": "opposite", "nr": "near",
}


def normalize_address(raw_address: str) -> str:
    text = _unicode_normalize(raw_address)
    text = _casefold(text)
    text = _normalize_punctuation(text)
    tokens = [_ADDRESS_ABBREV_MAP.get(tok, tok) for tok in text.split()]
    text = " ".join(tokens)
    return _normalize_whitespace(text)

!pip install aksharamukha

_SANSCRIPT_SCHEME = {
    "devanagari": "DEVANAGARI",
    "gujarati": "GUJARATI",
    "gurmukhi": "GURMUKHI",
    "bengali": "BENGALI",
    "kannada": "KANNADA",
    "malayalam": "MALAYALAM",
    "telugu": "TELUGU",

}


def transliterate(text: str, script: str) -> Optional[str]:
    """
    Deterministic, library-based transliteration (not model-based) so it's
    fast enough to run over the full dataset and fully reproducible for the
    methodology write-up. Returns None if the script isn't supported or the
    library isn't installed — callers must keep the original-script field
    regardless, per the earlier discussion: transliteration is an ADDITION,
    never a replacement for the original.
    """
    if not _HAS_INDIC or script not in _SANSCRIPT_SCHEME:
        return None
    try:
        src_scheme = getattr(sanscript, _SANSCRIPT_SCHEME[script])
        return sanscript.transliterate(text, src_scheme, sanscript.ITRANS).lower()
    except Exception:
        return None

try:
    from aksharamukha import transliterate as aksharamukha_translit
    _HAS_AKSHARAMUKHA = True
except ImportError:
    _HAS_AKSHARAMUKHA = False

def transliterate_tamil(text: str) -> Optional[str]:
    if not _HAS_AKSHARAMUKHA:
        return None
    try:
        return aksharamukha_translit.process("Tamil", "ISO", text).lower()
    except Exception:
        return None

_SCRIPT_TO_TRANSLIT_FN = {
    "tamil": transliterate_tamil,
    **{s: (lambda t, s=s: transliterate(t, s)) for s in _SANSCRIPT_SCHEME},
}

def transliterate_mixed(text: str) -> Optional[str]:
    """Splits mixed-script text into runs by script, transliterates each
    non-Latin run with its matching function, leaves Latin runs as-is."""
    if not text:
        return None
    runs, buf, cur_script = [], "", None
    for ch in text:
        s = detect_script(ch) if ch.strip() else cur_script
        if s != cur_script and buf:
            runs.append((cur_script, buf))
            buf = ""
        cur_script = s
        buf += ch
    if buf:
        runs.append((cur_script, buf))

    out = []
    for script, chunk in runs:
        fn = _SCRIPT_TO_TRANSLIT_FN.get(script)
        out.append(fn(chunk) if fn else chunk)
    result = " ".join(p for p in out if p).strip()
    return _normalize_whitespace(result) if result else None

def phonetic_code(text: str) -> Optional[str]:
    """
    Metaphone-style code on the Latin/transliterated text — catches spelling
    drift transliteration alone won't normalize (e.g. 'Sanav' vs 'Saanav').
    """
    if not text or not _HAS_JELLYFISH:
        return None
    try:
        return jellyfish.metaphone(text)
    except Exception:
        return None

@dataclass
class PipelineConfig:
    suffix_map: dict = field(default_factory=lambda: dict(_SEED_SUFFIX_MAP))


def preprocess_source(df: pd.DataFrame, config: Optional[PipelineConfig] = None) -> pd.DataFrame:
    cfg = config or PipelineConfig()
    out = df.copy()

    # ---- Stage 1: structured extraction (on RAW fields) ----
    out["name_domain"] = out["business_name"].apply(extract_domain)
    out["address_domain"] = out["business_address"].apply(extract_domain)
    out["domain"] = out["name_domain"].combine_first(out["address_domain"])
    out["has_repeated_token"] = out["business_name"].apply(has_repeated_token)
    out["address_numeric_tokens"] = out["business_address"].apply(extract_numeric_tokens)

    # ---- Stage 2: script detection (per field, independently) ----
    out["script_name"] = out["business_name"].apply(detect_script)
    out["script_address"] = out["business_address"].apply(detect_script)

    # ---- Stage 3a: name normalization (script-aware, see normalize_name) ----
    out["normalized_name"] = out.apply(
        lambda r: normalize_name(r["business_name"], cfg.suffix_map, r["script_name"])[0],
        axis=1,
    )
    out["normalized_name_no_suffix"] = out["normalized_name"].apply(strip_suffix)
    out["normalized_name_deduped"] = out["normalized_name"].apply(dedupe_repeated_tokens)

    # ---- Stage 3b: address normalization ----
    out["normalized_address"] = out["business_address"].apply(normalize_address)

    # ---- Stage 4: transliteration + phonetic code (non-Latin fields only) ----
    def _translit_field_row(row, text_col, script_col):
      script = row[script_col]
      text = row[text_col]
      if script == "tamil":
          return transliterate_tamil(text)
      if script in _SANSCRIPT_SCHEME:
          return transliterate(text, script)
      if script == "mixed":
          return transliterate_mixed(text)
      return None

    out["translit_name"] = out.apply(lambda r: _translit_field_row(r, "business_name", "script_name"), axis=1)
    out["translit_address"] = out.apply(lambda r: _translit_field_row(r, "business_address", "script_address"), axis=1)

    # light cleanup on the transliterated form only (already Latin-script
    # ASCII from the library, so punctuation/whitespace pass is safe here)
    out["translit_name"] = out["translit_name"].apply(
        lambda t: _normalize_whitespace(_normalize_punctuation(t))
        if isinstance(t, str) and t else None
    )
    out["translit_address"] = out["translit_address"].apply(
        lambda t: _normalize_whitespace(_normalize_punctuation(t))
        if isinstance(t, str) and t else None
    )

    # phonetic code computed on whichever Latin-script text is available:
    # translit_name if we transliterated, else normalized_name directly
    out["phonetic_code"] = out.apply(
        lambda r: phonetic_code(r["translit_name"] or r["normalized_name"]),
        axis=1,
    )
    out["phonetic_code_address"] = out.apply(
        lambda r: phonetic_code(r["translit_address"] or r["normalized_address"]),
        axis=1,
    )

    return out

if __name__ == "__main__":
    sample = pd.DataFrame({
        "entity_id": ["S2-1", "S2-2", "S2-3", "S2-4"],
        "business_name": [
            "SHIVSHAKTI VIDYALAYA VIDYALAYA OVERSEAS CORPORATION | www.shivshakti.com",
            "सन कंस्ट्रक्शंस प्राइवेट लिमिटेड",
            "Keystone Odyssey Odyssey LLC",
            "heassociates.com",
        ],
        "business_address": [
            "H.NO 204 C ROAD HOSHIARPUR, PUNJAB, Punjab India",
            "43 SUKH SAMRUDDHI, Maharashtra, PUNE REGION, PUNE",
            "1418 MEADOWBROOK DR, JOHNSON CITY, TN US",
            "599 PEASE HILL ROAD, HORICON, NY US",
        ],
        "country": ["India", "India", "US", "US"],
    })

    result = preprocess_source(sample)
    pd.set_option("display.max_colwidth", 60)
    print(result[[
        "entity_id", "domain", "script_name", "normalized_name",
        "normalized_name_deduped", "translit_name", "phonetic_code",
        "normalized_address", "address_numeric_tokens", "has_repeated_token",
    ]].to_string(index=False))

# Take the first 5000 rows of df2 for processing as requested
df2_5k = df2.head(5000).copy()

print("Preprocessing the first 5,000 rows of df2 using the defined pipeline:")
processed_df2_5k = preprocess_source(df2_5k)

print("Displaying a sample of the processed first 5,000 rows of df2:")
pd.set_option("display.max_colwidth", 60)
display(processed_df2_5k[[
    "entity_id",
    "domain",
    "script_name",
    "normalized_name",
    "normalized_name_deduped",
    "translit_name",
    "phonetic_code",
    "script_address",
    "normalized_address",
    "translit_address",
    "phonetic_code_address",
    "address_numeric_tokens",
    "has_repeated_token",
]].head())

output_path = '/content/drive/MyDrive/Amazon ML Challenge/processed_df2_5k.tsv'
processed_df2_5k.to_csv(output_path, sep='\t', index=False)
print(f"Processed df2_5k saved to: {output_path}")