# -*- coding: utf-8 -*-
"""Copy of preprocess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13qedihFMJFK_VOFtzNRQqP0e6kM-Zvpq
"""

pip install jellyfish indic-transliteration aksharamukha --break-system-packages

from google.colab import drive
drive.mount('/content/drive')

source1 = '/content/drive/MyDrive/Amazon ML Challenge/student_resource/dataset/train/train_source1.tsv'
source2 = '/content/drive/MyDrive/Amazon ML Challenge/student_resource/dataset/train/train_source2.tsv'
source3 = '/content/drive/MyDrive/Amazon ML Challenge/student_resource/dataset/train/train_source3.tsv'
gt = '/content/drive/MyDrive/Amazon ML Challenge/student_resource/dataset/train/train_ground_truth.tsv'
test1 = '/content/drive/MyDrive/Amazon ML Challenge/student_resource/dataset/test/test_source1.tsv'
test2 = '/content/drive/MyDrive/Amazon ML Challenge/student_resource/dataset/test/test_source2.tsv'
test3 = '/content/drive/MyDrive/Amazon ML Challenge/student_resource/dataset/test/test_source3.tsv'

import pandas as pd
import re
def load_source_tsv(path: str) -> pd.DataFrame:
    """
    Load a source file with the exact dtype/NA handling entity resolution
    needs: keep empty strings as empty strings (not NaN) so every .str
    method downstream is safe, but track true missingness explicitly first.
    """
    df = pd.read_csv(path, sep="\t", dtype=str, keep_default_na=False)
    for col in ("business_name", "business_address"):
        if col in df.columns:
            df[f"{col}_missing"] = df[col].isna() | (df[col].str.strip() == "")
            df[col] = df[col].fillna("")
    return df

try:

    df = load_source_tsv(source1)
    print(f"Successfully loaded data from '{source1}'. First 5 rows:")
    display(df.head())
except FileNotFoundError:
    print(f"Error: The file at '{source1}' was not found. Please check the path.")
except Exception as e:
    print(f"An error occurred while loading the TSV: {e}")

try:
    df2 = load_source_tsv(source2)
    print(f"Successfully loaded data from '{source2}'. First 5 rows:")
    display(df2.head())
except FileNotFoundError:
    print(f"Error: The file at '{source2}' was not found. Please check the path.")
except Exception as e:
    print(f"An error occurred while loading the TSV: {e}")

try:
    df3 = load_source_tsv(source3)
    print(f"Successfully loaded data from '{source3}'. First 5 rows:")
    display(df3.head())
except FileNotFoundError:
    print(f"Error: The file at '{source3}' was not found. Please check the path.")
except Exception as e:
    print(f"An error occurred while loading the TSV: {e}")

try:
    # Load the ground truth file
    df_gt = pd.read_csv(gt, sep='\t')
    print(f"Successfully loaded the ground truth file from '{gt}'. First 5 rows:")
    display(df_gt.head())
except FileNotFoundError:
    print(f"Error: The ground truth file at '{gt}' was not found. Please check the path.")
except Exception as e:
    print(f"An error occurred while loading the ground truth TSV: {e}")

import unicodedata
from collections import Counter

import numpy as np

try:
    import jellyfish
    HAVE_JELLYFISH = True
except ImportError:
    HAVE_JELLYFISH = False

try:
    from indic_transliteration import sanscript
    HAVE_INDIC = True
except ImportError:
    HAVE_INDIC = False

import re
import time
import unicodedata
from collections import Counter
from functools import lru_cache

import numpy as np
import pandas as pd

try:
    import jellyfish
    HAVE_JELLYFISH = True
except ImportError:
    HAVE_JELLYFISH = False

try:
    from indic_transliteration import sanscript
    HAVE_INDIC = True
except ImportError:
    HAVE_INDIC = False


# ============================================================
# CONFIG
# ============================================================

PROFILE = True

# Your EDA shows virtually all non-Latin data is from India.
# Keep this True for the fastest production path.
INDIA_ONLY_TRANSLITERATION = True

# Your EDA found a few US exceptions.
# Set this to True if you want those rare rows checked too.
CHECK_NON_INDIA_FOR_INDIC = False

# Cache size. Increase if RAM allows.
CACHE_SIZE = 300_000


# ============================================================
# CONSTANTS
# ============================================================

SUFFIX_MAP = {
    r"\bpvt\.?\s+ltd\.?\b": "private limited",
    r"\bprivate\s+ltd\.?\b": "private limited",
    r"\bpublic\s+limited\b": "public limited",
    r"\bl\s+c\b": "llc",
    r"\bs\s+a\s+s\b": "sas",
    r"\ba\s+s\b": "sas",
    r"\br\s+l\b": "sarl",

    r"प्राइवेट\s+लिमिटेड": "private limited",
    r"प्रा\s*लि": "private limited",

    r"\bpvt\.?\b": "private",
    r"\bltd\.?\b": "limited",
    r"\bllc\b": "llc",
    r"\binc\.?\b": "inc",
    r"\bcorp\.?\b": "corporation",
    r"\bco\.?\b": "company",
    r"\bllp\b": "llp",
    r"\blp\b": "lp",
    r"\bgmbh\b": "gmbh",
    r"\bsarl\b": "sarl",
    r"\bsas\b": "sas",
    r"\bs\.a\.s\.?\b": "sas",
    r"\bsasu\b": "sasu",
    r"\beurl\b": "eurl",
    r"\bsci\b": "sci",
    r"\bsa\b": "sa",

    r"लिमिटेड": "limited",
    r"\bलि\b": "limited",
}


STREET_MAP = {
    r"\brd\.?\b": "road",
    r"\bst\.?\b": "street",
    r"\bave\.?\b": "avenue",
    r"\bblvd\.?\b": "boulevard",
    r"\bdr\.?\b": "drive",
    r"\bln\.?\b": "lane",
    r"\bct\.?\b": "court",
    r"\bpl\.?\b": "place",
    r"\bapt\.?\b": "apartment",
    r"\bbldg\.?\b": "building",
    r"\bhwy\.?\b": "highway",
    r"\brue\b": "rue",
    r"\bav\.?\b": "avenue",
    r"\bbd\.?\b": "boulevard",
    r"\ballée\b": "allee",
    r"\bal lee\b": "allee",
    r"\ball\.?\b": "allee",
    r"\bimpasse\b": "impasse",
    r"\broute\b": "route",
}


SUFFIX_TOKENS = set(SUFFIX_MAP.values())


# ============================================================
# REGEXES
# ============================================================

UNIT_PATTERN = re.compile(
    r"\b(?:(?:unit|apt|apartment|suite|ste|#)\s*[:\-]?\s*)+([a-z0-9\-]+)",
    re.IGNORECASE,
)

LEADING_JUNK_PATTERN = re.compile(
    r"^[^a-zA-Z0-9\u0900-\u0DFF]+"
)

PUNCT_PATTERN = re.compile(
    r"[.,;:()[\]{}\"\'\`|]"
)

AMP_PATTERN = re.compile(r"&")

WHITESPACE_PATTERN = re.compile(r"\s+")

URL_RE = re.compile(
    r"(?:https?://)?(?:www\.)?"
    r"([a-z0-9][a-z0-9\-]*\.[a-z]{2,}(?:\.[a-z]{2,})?)",
    re.IGNORECASE,
)

EMAIL_RE = re.compile(
    r"[\w.+-]+@([\w-]+\.[\w.-]+)"
)

NUMERIC_TOKEN_RE = re.compile(
    r"\b\d[\d/\-]*\b"
)


# ============================================================
# SCRIPT RANGES
# ============================================================

SCRIPT_RANGES = {
    "devanagari": (0x0900, 0x097F),
    "bengali": (0x0980, 0x09FF),
    "gurmukhi": (0x0A00, 0x0A7F),
    "gujarati": (0x0A80, 0x0AFF),
    "tamil": (0x0B80, 0x0BFF),
    "telugu": (0x0C00, 0x0C7F),
    "kannada": (0x0C80, 0x0CFF),
    "malayalam": (0x0D00, 0x0D7F),
}


# One regex for "does this contain any Indic character?"
INDIC_ANY_RE = re.compile(
    r"[\u0900-\u0DFF]"
)


# Individual script regexes.
SCRIPT_REGEXES = {
    name: re.compile(
        f"[\\u{lo:04X}-\\u{hi:04X}]"
    )
    for name, (lo, hi) in SCRIPT_RANGES.items()
}


# Character → script lookup.
#
# This is the fast path.
#
# Example:
#   र -> devanagari
#   त -> tamil
#   क -> telugu
#   क -> kannada
#
SCRIPT_BY_CHAR = {}

for script, (lo, hi) in SCRIPT_RANGES.items():
    for codepoint in range(lo, hi + 1):
        SCRIPT_BY_CHAR[chr(codepoint)] = script


# ============================================================
# TRANSLITERATION SCHEMES
# ============================================================

SANSCRIPT_SCHEME = {
    "devanagari": "DEVANAGARI",
    "gujarati": "GUJARATI",
    "gurmukhi": "GURMUKHI",
    "bengali": "BENGALI",
    "kannada": "KANNADA",
    "malayalam": "MALAYALAM",
    "telugu": "TELUGU",
    "tamil":"TAMIL"
}


# ============================================================
# SCHWA CLEANING
# ============================================================

SCHWA_STRIP_RE = re.compile(
    r"(?<=[bcdfghjklmnpqrstvwxyz])a\b"
)

SCHWA_PROTECT = {
    "a",
    "sea",
    "tea",
    "yoga",
    "pizza",
    "plaza",
    "india",
    "asia",
    "africa",
    "america",
    "data",
    "media",
    "extra",
    "camera",
    "opera",
    "banana",
    "pasta",
    "visa",
    "gala",
    "vega",
    "nova",
    "delta",
    "omega",
    "sigma",
    "alpha",
    "beta",
    "theta",
}


RESIDUAL_SCRIPT_RE = re.compile(
    r"[\u0900-\u097F"
    r"\u0980-\u09FF"
    r"\u0A00-\u0A7F"
    r"\u0A80-\u0AFF"
    r"\u0B80-\u0BFF"
    r"\u0C00-\u0C7F"
    r"\u0C80-\u0CFF"
    r"\u0D00-\u0D7F]"
)


# ============================================================
# COMBINED DICTIONARY REGEX
# ============================================================

def build_combined_regex(mapping):
    return re.compile(
        "(" +
        "|".join(
            f"({pattern})"
            for pattern in mapping.keys()
        ) +
        ")"
    )


SUFFIX_COMBINED = build_combined_regex(SUFFIX_MAP)
STREET_COMBINED = build_combined_regex(STREET_MAP)

SUFFIX_REPLACEMENTS = list(SUFFIX_MAP.values())
STREET_REPLACEMENTS = list(STREET_MAP.values())


def make_combined_replacer(replacements):

    def replacer(match):

        groups = match.groups()

        for i, value in enumerate(groups[1:]):

            if value is not None:
                return replacements[i]

        return match.group(0)

    return replacer


SUFFIX_REPLACER = make_combined_replacer(
    SUFFIX_REPLACEMENTS
)

STREET_REPLACER = make_combined_replacer(
    STREET_REPLACEMENTS
)


# ============================================================
# BASIC STRING HELPERS
# ============================================================

def normalize_whitespace_str(text):

    return WHITESPACE_PATTERN.sub(
        " ",
        text
    ).strip()


def normalize_punctuation_str(text):

    text = AMP_PATTERN.sub(
        " and ",
        text
    )

    text = PUNCT_PATTERN.sub(
        " ",
        text
    )

    return normalize_whitespace_str(text)


def clean_transliteration(text):

    if not text:
        return text

    words = []

    for word in text.split():

        if word in SCHWA_PROTECT or len(word) <= 3:
            words.append(word)
            continue

        stripped = SCHWA_STRIP_RE.sub(
            "",
            word
        )

        words.append(
            stripped if stripped else word
        )

    return " ".join(words)

def strip_latin_diacritics(text):
    """
    Convert Latin characters with diacritics to plain ASCII.

    Examples:
        ḷ -> l
        ō -> o
        ṉ -> n
        ā -> a
    """
    if not text:
        return text

    normalized = unicodedata.normalize("NFKD", text)

    return "".join(
        ch for ch in normalized
        if not unicodedata.combining(ch)
    )

def strip_residual_script(text):

    if not text:
        return text

    text = RESIDUAL_SCRIPT_RE.sub(
        "",
        text
    )

    return normalize_whitespace_str(text)


# ============================================================
# BASIC NORMALIZATION
# ============================================================

def unicode_normalize_series(series):

    return series.map(
        lambda x:
            unicodedata.normalize("NFKC", x)
            if isinstance(x, str)
            else x
    )


def basic_clean(series):

    series = unicode_normalize_series(series)

    series = series.str.casefold()

    series = series.str.replace(
        LEADING_JUNK_PATTERN,
        "",
        regex=True
    )

    series = series.str.replace(
        WHITESPACE_PATTERN,
        " ",
        regex=True
    ).str.strip()

    series = series.str.replace(
        AMP_PATTERN,
        " and ",
        regex=True
    )

    series = series.str.replace(
        PUNCT_PATTERN,
        " ",
        regex=True
    )

    series = series.str.replace(
        WHITESPACE_PATTERN,
        " ",
        regex=True
    ).str.strip()

    return series


# ============================================================
# DICTIONARY NORMALIZATION
# ============================================================

def apply_suffix_map(series):

    return series.str.replace(
        SUFFIX_COMBINED,
        SUFFIX_REPLACER,
        regex=True
    ).str.replace(
        WHITESPACE_PATTERN,
        " ",
        regex=True
    ).str.strip()


def apply_street_map(series):

    return series.str.replace(
        STREET_COMBINED,
        STREET_REPLACER,
        regex=True
    ).str.replace(
        WHITESPACE_PATTERN,
        " ",
        regex=True
    ).str.strip()


# ============================================================
# DOMAIN
# ============================================================

def extract_domain(text):

    if not text:
        return None

    match = EMAIL_RE.search(text)

    if match:
        return match.group(1).lower().rstrip(".")

    match = URL_RE.search(text)

    if match:

        domain = match.group(1).lower().rstrip(".")

        if "." in domain:
            return domain

    return None


# ============================================================
# SCRIPT DETECTION
# ============================================================

def first_meaningful_char(text):

    if not text:
        return None

    for char in text:

        if char.isspace():
            continue

        if char.isalnum():
            return char

    return None


def script_from_first_character(text):

    first = first_meaningful_char(text)

    if first is None:
        return "unknown"

    return SCRIPT_BY_CHAR.get(
        first,
        "latin"
    )


@lru_cache(maxsize=CACHE_SIZE)
def detect_indic_script_full(text):

    if not text:
        return "unknown"

    counts = {}

    for script, regex in SCRIPT_REGEXES.items():

        count = len(
            regex.findall(text)
        )

        if count:
            counts[script] = count

    if not counts:
        return "latin"

    dominant, dominant_count = max(
        counts.items(),
        key=lambda x: x[1]
    )

    total = sum(
        counts.values()
    )

    if (
        len(counts) > 1
        and dominant_count / total < 0.6
    ):
        return "mixed"

    return dominant


@lru_cache(maxsize=CACHE_SIZE)
def detect_script_fast(text, country):

    if not text:
        return "missing"

    country = (
        country.casefold()
        if isinstance(country, str)
        else ""
    )

    # --------------------------------------------------------
    # Fastest path
    # --------------------------------------------------------

    if (
        INDIA_ONLY_TRANSLITERATION
        and country != "india"
        and not CHECK_NON_INDIA_FOR_INDIC
    ):
        return "latin"

    # --------------------------------------------------------
    # First-character fast path
    # --------------------------------------------------------

    script = script_from_first_character(
        text
    )

    if script != "latin":
        return script

    # --------------------------------------------------------
    # Latin first character.
    #
    # Most strings end here.
    #
    # Only run the Unicode search if necessary.
    # --------------------------------------------------------

    if not INDIC_ANY_RE.search(text):
        return "latin"

    # --------------------------------------------------------
    # Mixed-script fallback
    # --------------------------------------------------------

    return detect_indic_script_full(text)


# ============================================================
# TRANSLITERATION
# ============================================================

@lru_cache(maxsize=CACHE_SIZE)
def transliterate_itrans(
    text,
    script
):

    if (
        not HAVE_INDIC
        or script not in SANSCRIPT_SCHEME
    ):
        return text

    try:

        source_scheme = getattr(
            sanscript,
            SANSCRIPT_SCHEME[script]
        )

        return sanscript.transliterate(
            text,
            source_scheme,
            sanscript.ITRANS
        ).lower()

    except Exception:

        return text


@lru_cache(maxsize=CACHE_SIZE)
def transliterate_tamil(text):

    if not HAVE_AKSHARAMUKHA:
        return text

    try:

        return aksharamukha_translit.process(
            "Tamil",
            "ISO",
            text
        ).lower()

    except Exception:

        return text

def transliterate_script(
    text,
    script
):

    if not text:
        return text

    if script in (
        "latin",
        "unknown",
        "missing"
    ):
        return text

    if script in SANSCRIPT_SCHEME:

        result = transliterate_itrans(
            text,
            script
        )

        # Tamil transliteration can produce
        # Latin characters with diacritics:
        # ḷ, ō, ṉ, ā, etc.
        #
        # Convert them to plain ASCII:
        # l, o, n, a, etc.
        if script == "tamil":
            result = strip_latin_diacritics(result)

        return result

    if script == "mixed":

        return transliterate_mixed(
            text
        )

    return text


@lru_cache(maxsize=CACHE_SIZE)
def transliterate_mixed(text):

    if not text:
        return text

    output = []

    current_script = None
    buffer = []

    def flush():

        nonlocal buffer
        nonlocal current_script

        if not buffer:
            return

        chunk = "".join(buffer)

        if current_script in (
            "latin",
            "unknown",
            None
        ):

            output.append(chunk)

        else:

            output.append(
                transliterate_script(
                    chunk,
                    current_script
                )
            )

        buffer = []

    for char in text:

        if char.isspace():

            buffer.append(char)
            continue

        script = SCRIPT_BY_CHAR.get(
            char,
            "latin"
        )

        if script != current_script:

            flush()

            current_script = script

        buffer.append(char)

    flush()

    return "".join(output)


# ============================================================
# ONE-PASS DETECTION + TRANSLITERATION
# ============================================================

@lru_cache(maxsize=CACHE_SIZE)
def detect_and_transliterate(
    text,
    country
):

    if not text:
        return text, "missing"

    script = detect_script_fast(
        text,
        country
    )

    if script == "latin":

        return text, "latin"

    transliterated = transliterate_script(
        text,
        script
    )

    transliterated = normalize_whitespace_str(
        normalize_punctuation_str(
            clean_transliteration(
                strip_residual_script(
                    transliterated
                )
            )
        )
    )

    return transliterated, script


def process_transliteration_series(
    text_series,
    country_series
):

    results = []
    scripts = []

    for text, country in zip(
        text_series,
        country_series
    ):

        if not isinstance(text, str) or not text:

            results.append(text)
            scripts.append("missing")
            continue

        transliterated, script = (
            detect_and_transliterate(
                text,
                country
            )
        )

        results.append(
            transliterated
        )

        scripts.append(
            script
        )

    return (
        pd.Series(
            results,
            index=text_series.index
        ),
        pd.Series(
            scripts,
            index=text_series.index
        )
    )


# ============================================================
# NAME PROCESSING
# ============================================================

SUFFIX_STRIP_PATTERN = re.compile(
    r"\b(" +
    "|".join(
        re.escape(x)
        for x in SUFFIX_TOKENS
    ) +
    r")\b"
)


def strip_suffixes(series):

    return series.str.replace(
        SUFFIX_STRIP_PATTERN,
        "",
        regex=True
    ).str.replace(
        WHITESPACE_PATTERN,
        " ",
        regex=True
    ).str.strip()


def sorted_tokens(series):

    return series.map(
        lambda x:
            " ".join(
                sorted(x.split())
            )
            if isinstance(x, str) and x
            else x
    )


def phonetic_code(series):

    if not HAVE_JELLYFISH:

        return pd.Series(
            np.nan,
            index=series.index
        )

    return series.map(
        lambda x:
            jellyfish.nysiis(x)
            if isinstance(x, str) and x
            else np.nan
    )


def repeated_token(series):

    def check(text):

        if not text:
            return False

        tokens = text.lower().split()

        if len(tokens) < 2:
            return False

        counts = Counter(tokens)

        return any(
            count > 1
            for token, count
            in counts.items()
            if len(token) > 2
        )

    return series.map(check)


# ============================================================
# ADDRESS PROCESSING
# ============================================================

def extract_unit(series):

    return series.map(
        lambda x:
            (
                match.group(1)
                if (
                    match := UNIT_PATTERN.search(x)
                )
                else np.nan
            )
            if isinstance(x, str)
            else np.nan
    )


def remove_unit(series):

    return series.str.replace(
        UNIT_PATTERN,
        " ",
        regex=True
    ).str.replace(
        WHITESPACE_PATTERN,
        " ",
        regex=True
    ).str.strip()


def extract_numeric_tokens(series):

    return series.map(
        lambda x:
            NUMERIC_TOKEN_RE.findall(x)
            if isinstance(x, str) and x
            else []
    )


# ============================================================
# MAIN PREPROCESSOR
# ============================================================

def preprocess_source(
    df,
    id_col="entity_id"
):

    timings = {}

    total_start = time.perf_counter()

    out = df.copy()

    # --------------------------------------------------------
    # COUNTRY
    # --------------------------------------------------------

    start = time.perf_counter()

    country_normalized = (
        out["country"]
        .fillna("")
        .astype(str)
        .str.strip()
        .str.casefold()
    )

    out["country_normalized"] = (
        country_normalized
    )

    timings["country"] = (
        time.perf_counter() - start
    )

    # --------------------------------------------------------
    # MISSING FLAGS
    # --------------------------------------------------------

    start = time.perf_counter()

    name_raw = out["business_name"]

    address_raw = out["business_address"]

    out["name_is_missing"] = (
        name_raw.isna()
        |
        name_raw.astype(str)
        .str.strip()
        .eq("")
    )

    out["address_is_missing"] = (
        address_raw.isna()
        |
        address_raw.astype(str)
        .str.strip()
        .eq("")
    )

    name_filled = name_raw.fillna("")

    address_filled = address_raw.fillna("")

    timings["missing flags"] = (
        time.perf_counter() - start
    )

    # --------------------------------------------------------
    # RAW EXTRACTION
    # --------------------------------------------------------

    start = time.perf_counter()

    out["domain"] = (
        name_filled.map(
            extract_domain
        )
    )

    out["has_repeated_token"] = (
        repeated_token(
            name_filled
        )
    )

    out["address_numeric_tokens"] = (
        extract_numeric_tokens(
            address_filled
        )
    )

    timings["raw extraction"] = (
        time.perf_counter() - start
    )

    # ========================================================
    # NAME
    # ========================================================

    # --------------------------------------------------------
    # Name normalization
    # --------------------------------------------------------

    start = time.perf_counter()

    name_no_domain = (
        name_filled
        .str.replace(
            EMAIL_RE,
            " ",
            regex=True
        )
        .str.replace(
            URL_RE,
            " ",
            regex=True
        )
    )

    name_clean = basic_clean(
        name_no_domain
    )

    name_clean = (
        name_clean
        .str.replace(
            r"#\w*",
            " ",
            regex=True
        )
        .str.replace(
            WHITESPACE_PATTERN,
            " ",
            regex=True
        )
        .str.strip()
    )

    out["name_normalized"] = (
        apply_suffix_map(
            name_clean
        )
    )

    out["name_suffix_stripped"] = (
        strip_suffixes(
            out["name_normalized"]
        )
    )

    out["name_sorted_tokens"] = (
        sorted_tokens(
            out["name_suffix_stripped"]
        )
    )

    timings["name normalization"] = (
        time.perf_counter() - start
    )

    # --------------------------------------------------------
    # Name transliteration
    #
    # IMPORTANT:
    # Detection + transliteration are now one logical pass.
    # --------------------------------------------------------

    start = time.perf_counter()

    (
        out["name_transliterated"],
        out["script_name"]
    ) = process_transliteration_series(
        out["name_normalized"],
        country_normalized
    )

    out["name_transliterated_suffix_stripped"] = (
        strip_suffixes(
            out["name_transliterated"]
        )
    )

    timings["name transliteration"] = (
        time.perf_counter() - start
    )

    # --------------------------------------------------------
    # Name phonetic
    # --------------------------------------------------------

    start = time.perf_counter()

    out["name_phonetic"] = (
        phonetic_code(
            out["name_transliterated"]
        )
    )

    timings["name phonetic"] = (
        time.perf_counter() - start
    )

    # ========================================================
    # ADDRESS
    # ========================================================

    # --------------------------------------------------------
    # Address normalization
    # --------------------------------------------------------

    start = time.perf_counter()

    address_clean = basic_clean(
        address_filled
    )

    address_clean = apply_street_map(
        address_clean
    )

    out["unit_value"] = (
        extract_unit(
            address_clean
        )
    )

    address_no_unit = remove_unit(
        address_clean
    )

    out["address_normalized"] = (
        address_no_unit
        .str.replace(
            r"#\w*",
            " ",
            regex=True
        )
        .str.replace(
            WHITESPACE_PATTERN,
            " ",
            regex=True
        )
        .str.strip()
    )

    timings["address normalization"] = (
        time.perf_counter() - start
    )

    # --------------------------------------------------------
    # Address transliteration
    # --------------------------------------------------------

    start = time.perf_counter()

    (
        out["address_transliterated"],
        out["script_address"]
    ) = process_transliteration_series(
        out["address_normalized"],
        country_normalized
    )

    timings["address transliteration"] = (
        time.perf_counter() - start
    )

    # --------------------------------------------------------
    # Missing-value cleanup
    # --------------------------------------------------------

    out.loc[
        out["name_is_missing"],
        [
            "name_normalized",
            "name_suffix_stripped",
            "name_sorted_tokens",
            "name_transliterated",
            "name_transliterated_suffix_stripped",
            "name_phonetic",
        ]
    ] = np.nan

    out.loc[
        out["address_is_missing"],
        [
            "unit_value",
            "address_normalized",
            "address_transliterated",
        ]
    ] = np.nan

    missing_addresses = int(
        out["address_is_missing"].sum()
    )

    if missing_addresses:

        out.loc[
            out["address_is_missing"],
            "address_numeric_tokens"
        ] = pd.Series(
            [
                []
                for _ in range(missing_addresses)
            ],
            index=out.index[out["address_is_missing"]]
        )

    # --------------------------------------------------------
    # Final columns
    # --------------------------------------------------------

    final_cols = [
        id_col,

        "business_name",
        "business_address",
        "country",

        "name_is_missing",
        "address_is_missing",

        "script_name",
        "script_address",

        "name_normalized",
        "name_suffix_stripped",
        "name_sorted_tokens",

        "name_transliterated",
        "name_transliterated_suffix_stripped",
        "name_phonetic",

        "address_normalized",
        "address_transliterated",

        "address_numeric_tokens",
        "unit_value",

        "domain",
        "has_repeated_token",

        "country_normalized",
    ]

    final_cols = [
        col
        for col in final_cols
        if col in out.columns
    ]

    result = out[
        final_cols
    ]

    timings["total"] = (
        time.perf_counter() - total_start
    )

    # ========================================================
    # PROFILING
    # ========================================================

    if PROFILE:

        print()
        print(
            "======================================"
        )
        print(
            "       PREPROCESSING TIMING"
        )
        print(
            "======================================"
        )

        for key, value in timings.items():

            print(
                f"{key:30s}: "
                f"{value:9.2f} sec"
            )

        print(
            "======================================"
        )

        print(
            "\nCACHE STATISTICS"
        )

        print(
            "detect_script_fast:",
            detect_script_fast.cache_info()
        )

        print(
            "detect_indic_script_full:",
            detect_indic_script_full.cache_info()
        )

        print(
            "detect_and_transliterate:",
            detect_and_transliterate.cache_info()
        )

        print(
            "transliterate_itrans:",
            transliterate_itrans.cache_info()
        )

        print(
            "transliterate_tamil:",
            transliterate_tamil.cache_info()
        )

        print(
            "transliterate_mixed:",
            transliterate_mixed.cache_info()
        )

    return result

processed = preprocess_source(
    df2_5k
)

processed.to_csv(
    "/content/drive/MyDrive/Amazon ML Challenge/optimised df2.tsv",
    sep="\t",
    index=False
)


df2_5k = df2.head(5000).copy()

print("Preprocessing the first 5,000 rows of df2 using the defined pipeline:")
processed_df2_5k = preprocess_source(df2_5k)

print("Displaying a sample of the processed first 5,000 rows of df2:")
pd.set_option("display.max_colwidth", 60)
display(processed_df2_5k[[
    "entity_id",
    "domain",
    "script_name",
    "name_normalized",
    "name_transliterated",
    "name_phonetic",
    "script_address",
    "address_normalized",
    "address_transliterated",
    "address_numeric_tokens",
    "has_repeated_token",
]].head())

output_path = '/content/drive/MyDrive/Amazon ML Challenge/processed_df2_5k.tsv'
processed_df2_5k.to_csv(output_path, sep='\t', index=False)
print(f"Processed df2_5k saved to: {output_path}")
