# -*- coding: utf-8 -*-
"""Copy of preprocess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13qedihFMJFK_VOFtzNRQqP0e6kM-Zvpq
"""

pip install jellyfish indic-transliteration aksharamukha --break-system-packages

from google.colab import drive
drive.mount('/content/drive')

source1 = '/content/drive/MyDrive/Amazon ML Challenge/student_resource/dataset/train/train_source1.tsv'
source2 = '/content/drive/MyDrive/Amazon ML Challenge/student_resource/dataset/train/train_source2.tsv'
source3 = '/content/drive/MyDrive/Amazon ML Challenge/student_resource/dataset/train/train_source3.tsv'
gt = '/content/drive/MyDrive/Amazon ML Challenge/student_resource/dataset/train/train_ground_truth.tsv'
test1 = '/content/drive/MyDrive/Amazon ML Challenge/student_resource/dataset/test/test_source1.tsv'
test2 = '/content/drive/MyDrive/Amazon ML Challenge/student_resource/dataset/test/test_source2.tsv'
test3 = '/content/drive/MyDrive/Amazon ML Challenge/student_resource/dataset/test/test_source3.tsv'

import pandas as pd
import re
def load_source_tsv(path: str) -> pd.DataFrame:
    """
    Load a source file with the exact dtype/NA handling entity resolution
    needs: keep empty strings as empty strings (not NaN) so every .str
    method downstream is safe, but track true missingness explicitly first.
    """
    df = pd.read_csv(path, sep="\t", dtype=str, keep_default_na=False)
    for col in ("business_name", "business_address"):
        if col in df.columns:
            df[f"{col}_missing"] = df[col].isna() | (df[col].str.strip() == "")
            df[col] = df[col].fillna("")
    return df

try:

    df = load_source_tsv(source1)
    print(f"Successfully loaded data from '{source1}'. First 5 rows:")
    display(df.head())
except FileNotFoundError:
    print(f"Error: The file at '{source1}' was not found. Please check the path.")
except Exception as e:
    print(f"An error occurred while loading the TSV: {e}")

try:
    df2 = load_source_tsv(source2)
    print(f"Successfully loaded data from '{source2}'. First 5 rows:")
    display(df2.head())
except FileNotFoundError:
    print(f"Error: The file at '{source2}' was not found. Please check the path.")
except Exception as e:
    print(f"An error occurred while loading the TSV: {e}")

try:
    df3 = load_source_tsv(source3)
    print(f"Successfully loaded data from '{source3}'. First 5 rows:")
    display(df3.head())
except FileNotFoundError:
    print(f"Error: The file at '{source3}' was not found. Please check the path.")
except Exception as e:
    print(f"An error occurred while loading the TSV: {e}")

try:
    # Load the ground truth file
    df_gt = pd.read_csv(gt, sep='\t')
    print(f"Successfully loaded the ground truth file from '{gt}'. First 5 rows:")
    display(df_gt.head())
except FileNotFoundError:
    print(f"Error: The ground truth file at '{gt}' was not found. Please check the path.")
except Exception as e:
    print(f"An error occurred while loading the ground truth TSV: {e}")

import unicodedata
from collections import Counter

import numpy as np

try:
    import jellyfish
    HAVE_JELLYFISH = True
except ImportError:
    HAVE_JELLYFISH = False

try:
    from indic_transliteration import sanscript
    HAVE_INDIC = True
except ImportError:
    HAVE_INDIC = False

try:
    from aksharamukha import transliterate as aksharamukha_translit
    HAVE_AKSHARAMUKHA = True
except ImportError:
    HAVE_AKSHARAMUKHA = False


# ------------------------------------------------------------
# CONFIGURATION
# ------------------------------------------------------------

ENABLE_TRANSLITERATION = True
ENABLE_SORTED_TOKENS = True
ENABLE_PHONETIC = True


# ------------------------------------------------------------
# CONSTANTS / DICTIONARIES
# ------------------------------------------------------------

SUFFIX_MAP = {
    r"\bpvt\.?\s+ltd\.?\b": "private limited",
    r"\bprivate\s+ltd\.?\b": "private limited",
    r"\bpublic\s+limited\b": "public limited",
    r"\bl\s+c\b": "llc",
    r"\bs\s+a\s+s\b": "sas",
    r"\ba\s+s\b": "sas",
    r"\br\s+l\b": "sarl",
    r"प्राइवेट\s+लिमिटेड": "private limited",
    r"प्रा\s*लि": "private limited",

    r"\bpvt\.?\b": "private",
    r"\bltd\.?\b": "limited",
    r"\bllc\b": "llc",
    r"\binc\.?\b": "inc",
    r"\bcorp\.?\b": "corporation",
    r"\bco\.?\b": "company",
    r"\bllp\b": "llp",
    r"\blp\b": "lp",
    r"\bgmbh\b": "gmbh",
    r"\bsarl\b": "sarl",
    r"\bsas\b": "sas",
    r"\bs\.a\.s\.?\b": "sas",
    r"\bsasu\b": "sasu",
    r"\beurl\b": "eurl",
    r"\bsci\b": "sci",
    r"\bsa\b": "sa",
    r"लिमिटेड": "limited",
    r"\bलि\b": "limited",
}
SUFFIX_TOKENS = set(SUFFIX_MAP.values())
_SUFFIX_STRIP_PATTERN = re.compile(
    r"\b(" + "|".join(re.escape(t) for t in SUFFIX_TOKENS) + r")\b"
)

STREET_MAP = {
    r"\brd\.?\b": "road",
    r"\bst\.?\b": "street",
    r"\bave\.?\b": "avenue",
    r"\bblvd\.?\b": "boulevard",
    r"\bdr\.?\b": "drive",
    r"\bln\.?\b": "lane",
    r"\bct\.?\b": "court",
    r"\bpl\.?\b": "place",
    r"\bapt\.?\b": "apartment",
    r"\bbldg\.?\b": "building",
    r"\bhwy\.?\b": "highway",
    r"\brue\b": "rue",
    r"\bav\.?\b": "avenue",
    r"\bbd\.?\b": "boulevard",
    r"\ballée\b": "allee",
    r"\ballee\b": "allee",
    r"\ball\.?\b": "allee",
    r"\bimpasse\b": "impasse",
    r"\broute\b": "route",
}

UNIT_PATTERN = re.compile(
    r"\b(?:(?:unit|apt|apartment|suite|ste|#)\s*[:\-]?\s*)+([a-z0-9\-]+)",
    flags=re.IGNORECASE,
)

LEADING_JUNK_PATTERN = re.compile(r"^[^a-zA-Z0-9\u0900-\u097F\u0B80-\u0BFF\u0C80-\u0CFF]+")
PUNCT_PATTERN = re.compile(r"[.,;:()\[\]{}\"'`|]")
AMP_PATTERN = re.compile(r"&")
WHITESPACE_PATTERN = re.compile(r"\s+")

_URL_RE = re.compile(
    r"(?:https?://)?(?:www\.)?([a-z0-9][a-z0-9\-]*\.[a-z]{2,}(?:\.[a-z]{2,})?)",
    re.IGNORECASE,
)
_EMAIL_RE = re.compile(r"[\w.+-]+@([\w-]+\.[\w.-]+)")

_NUMERIC_TOKEN_RE = re.compile(r"\b\d[\d/\-]*\b")

_SCRIPT_RANGES = {
    "devanagari": (0x0900, 0x097F),
    "tamil": (0x0B80, 0x0BFF),
    "bengali": (0x0980, 0x09FF),
    "telugu": (0x0C00, 0x0C7F),
    "kannada": (0x0C80, 0x0CFF),
    "malayalam": (0x0D00, 0x0D7F),
    "gujarati": (0x0A80, 0x0AFF),
    "gurmukhi": (0x0A00, 0x0A7F),
}

_SANSCRIPT_SCHEME = {
    "devanagari": "DEVANAGARI",
    "gujarati": "GUJARATI",
    "gurmukhi": "GURMUKHI",
    "bengali": "BENGALI",
    "kannada": "KANNADA",
    "malayalam": "MALAYALAM",
    "telugu": "TELUGU",
}

# Trailing schwa-artifact cleanup after ITRANS transliteration.
# Targeted: only strips a bare trailing "a" that follows a consonant
# letter, and only when doing so still leaves a real word behind.
_SCHWA_STRIP_RE = re.compile(r"(?<=[bcdfghjklmnpqrstvwxyz])a\b")

# Common short/legit English words ending in "a" that must be
# protected from schwa-stripping (e.g. "india" must not -> "ind").
_SCHWA_PROTECT = {
    "a", "sea", "tea", "yoga", "pizza", "plaza", "india", "asia",
    "africa", "america", "data", "media", "extra", "camera", "opera",
    "banana", "pasta", "visa", "gala", "vega", "nova", "delta",
    "omega", "sigma", "alpha", "beta", "theta",
}

# Any Indic-script codepoint that survives transliteration (rare library
# gaps, e.g. candra-O vowel signs) is a leftover, not intended output.
_RESIDUAL_SCRIPT_RE = re.compile(
    r"[\u0900-\u097F\u0980-\u09FF\u0A00-\u0A7F\u0A80-\u0AFF"
    r"\u0B80-\u0BFF\u0C00-\u0C7F\u0C80-\u0CFF\u0D00-\u0D7F]"
)


def _strip_residual_script(text: str) -> str:
    if not text:
        return text
    return WHITESPACE_PATTERN.sub(" ", _RESIDUAL_SCRIPT_RE.sub("", text)).strip()


def _strip_schwa(word: str) -> str:
    if word in _SCHWA_PROTECT or len(word) <= 3:
        return word
    stripped = _SCHWA_STRIP_RE.sub("", word)
    return stripped if stripped else word


def clean_transliteration(text):
    """Light, targeted schwa cleanup on ITRANS output. Never touches
    already-Latin input (only called on transliterated strings)."""
    if not text:
        return text
    words = text.split()
    return " ".join(_strip_schwa(w) for w in words)


# ------------------------------------------------------------
# CORE TEXT CLEANUP
# ------------------------------------------------------------

def unicode_normalize(series: pd.Series) -> pd.Series:
    return series.astype(str).map(
        lambda x: unicodedata.normalize("NFKC", x) if pd.notna(x) else x
    )


def casefold_series(series: pd.Series) -> pd.Series:
    return series.astype(str).map(lambda x: x.casefold() if pd.notna(x) else x)


def strip_leading_junk(series: pd.Series) -> pd.Series:
    return series.str.replace(LEADING_JUNK_PATTERN, "", regex=True)


def normalize_whitespace(series: pd.Series) -> pd.Series:
    return series.str.replace(WHITESPACE_PATTERN, " ", regex=True).str.strip()


def normalize_punctuation(series: pd.Series) -> pd.Series:
    series = series.str.replace(AMP_PATTERN, " and ", regex=True)
    series = series.str.replace(PUNCT_PATTERN, " ", regex=True)
    return normalize_whitespace(series)


def apply_dictionary(series: pd.Series, mapping: dict) -> pd.Series:
    for pattern, replacement in mapping.items():
        series = series.str.replace(pattern, replacement, regex=True)
    return normalize_whitespace(series)


def basic_clean(series: pd.Series) -> pd.Series:
    s = unicode_normalize(series)
    s = casefold_series(s)
    s = strip_leading_junk(s)
    s = normalize_whitespace(s)
    s = normalize_punctuation(s)
    return s


# ------------------------------------------------------------
# DOMAIN EXTRACTION (fixed: removed from name_normalized after extraction)
# ------------------------------------------------------------

def extract_domain(text):
    if not text:
        return None
    m = _EMAIL_RE.search(text)
    if m:
        return m.group(1).lower().rstrip(".")
    m = _URL_RE.search(text)
    if m:
        domain = m.group(1).lower().rstrip(".")
        if "." in domain and not domain.replace(".", "").isdigit():
            return domain
    return None


def extract_domain_series(series: pd.Series) -> pd.Series:
    return series.map(extract_domain)


def remove_domain_fragment(series: pd.Series) -> pd.Series:
    """Strip an embedded URL/email domain fragment out of the raw text
    BEFORE normalization, so the domain never survives inside
    name_normalized. Runs on the raw (pre-clean) string since the URL
    regex expects real punctuation (dots, @, /)."""
    stripped = series.str.replace(_EMAIL_RE, " ", regex=True)
    stripped = stripped.str.replace(_URL_RE, " ", regex=True)
    return stripped


# ------------------------------------------------------------
# SCRIPT DETECTION
# ------------------------------------------------------------

def detect_script_one(text: str) -> str:
    if not text or not text.strip():
        return "unknown"
    counts = Counter()
    for ch in text:
        cp = ord(ch)
        if cp < 128:
            if ch.isalpha():
                counts["latin"] += 1
            continue
        for name, (lo, hi) in _SCRIPT_RANGES.items():
            if lo <= cp <= hi:
                counts[name] += 1
                break
    if not counts:
        return "unknown"
    dominant, dom_count = counts.most_common(1)[0]
    total = sum(counts.values())
    if dom_count / total < 0.6 and len(counts) > 1:
        return "mixed"
    return dominant


def detect_script_series(series: pd.Series) -> pd.Series:
    return series.map(lambda x: detect_script_one(x) if pd.notna(x) else "unknown")


# ------------------------------------------------------------
# TRANSLITERATION (ITRANS-based, per Section 2 of instructions)
# ------------------------------------------------------------

def _itrans_transliterate(text: str, script: str):
    if not HAVE_INDIC or script not in _SANSCRIPT_SCHEME:
        return None
    try:
        src_scheme = getattr(sanscript, _SANSCRIPT_SCHEME[script])
        return sanscript.transliterate(text, src_scheme, sanscript.ITRANS).lower()
    except Exception:
        return None


def _tamil_transliterate(text: str):
    if not HAVE_AKSHARAMUKHA:
        return None
    try:
        return aksharamukha_translit.process("Tamil", "ISO", text).lower()
    except Exception:
        return None


def _translit_run(script: str, chunk: str):
    if script == "tamil":
        return _tamil_transliterate(chunk)
    if script in _SANSCRIPT_SCHEME:
        return _itrans_transliterate(chunk, script)
    return None


def _transliterate_mixed(text: str):
    if not text:
        return None
    runs, buf, cur_script = [], "", None
    for ch in text:
        s = detect_script_one(ch) if ch.strip() else cur_script
        if s != cur_script and buf:
            runs.append((cur_script, buf))
            buf = ""
        cur_script = s
        buf += ch
    if buf:
        runs.append((cur_script, buf))

    out = []
    for script, chunk in runs:
        if script in ("latin", "unknown"):
            out.append(chunk)
        else:
            transliterated = _translit_run(script, chunk)
            # Fallback: if a non-Latin run survives transliteration
            # unexpectedly (library missing/unsupported script), keep
            # the original chunk rather than dropping it silently.
            out.append(transliterated if transliterated else chunk)
    result = " ".join(p for p in out if p and p.strip())
    return result.strip() if result else None


def transliterate_one(text, script):
    if not text or not text.strip():
        return None
    if script == "latin" or script == "unknown":
        return text
    if script == "tamil":
        result = _tamil_transliterate(text)
    elif script in _SANSCRIPT_SCHEME:
        result = _itrans_transliterate(text, script)
    elif script == "mixed":
        result = _transliterate_mixed(text)
    else:
        result = None
    # fallback: unsupported/failed transliteration -> keep original text
    # safely rather than losing the field
    if result is None:
        return text
    return result


def transliterate_series(text_series: pd.Series, script_series: pd.Series) -> pd.Series:
    """Vectorized-as-possible: only runs transliteration work on rows
    that are actually non-Latin, skipping already-Latin text entirely."""
    if not ENABLE_TRANSLITERATION:
        return text_series

    result = text_series.copy()
    non_latin_mask = ~script_series.isin(["latin", "unknown"]) & text_series.notna() & (text_series != "")

    if non_latin_mask.any():
        translit_vals = [
            transliterate_one(t, s)
            for t, s in zip(text_series[non_latin_mask], script_series[non_latin_mask])
        ]
        result.loc[non_latin_mask] = translit_vals

    # light cleanup + schwa-artifact trim, applied once to the whole
    # transliterated/Latin column (cheap ascii-only regex work)
    result = result.map(
        lambda x: _strip_residual_script(
            clean_transliteration(normalize_whitespace_str(normalize_punctuation_str(x)))
        )
        if isinstance(x, str) and x else x
    )
    return result


def normalize_whitespace_str(text: str) -> str:
    return WHITESPACE_PATTERN.sub(" ", text).strip()


def normalize_punctuation_str(text: str) -> str:
    text = AMP_PATTERN.sub(" and ", text)
    text = PUNCT_PATTERN.sub(" ", text)
    return normalize_whitespace_str(text)


# ------------------------------------------------------------
# NAME-SPECIFIC DERIVED FIELDS
# ------------------------------------------------------------

def strip_suffixes(series: pd.Series) -> pd.Series:
    return series.str.replace(_SUFFIX_STRIP_PATTERN, "", regex=True).pipe(normalize_whitespace)


def sorted_tokens(series: pd.Series) -> pd.Series:
    if not ENABLE_SORTED_TOKENS:
        return pd.Series([np.nan] * len(series), index=series.index)
    return series.map(
        lambda x: " ".join(sorted(x.split())) if pd.notna(x) and x else x
    )


def phonetic_code(series: pd.Series) -> pd.Series:
    """NYSIIS phonetic code, computed once on the transliterated/Latin
    name. Missing/empty values are skipped, never encoded."""
    if not ENABLE_PHONETIC or not HAVE_JELLYFISH:
        return pd.Series([np.nan] * len(series), index=series.index)
    return series.map(
        lambda x: jellyfish.nysiis(x) if pd.notna(x) and x else np.nan
    )


def has_repeated_token(series: pd.Series) -> pd.Series:
    def _check(text):
        if not text:
            return False
        tokens = text.lower().split()
        if len(tokens) < 2:
            return False
        counts = Counter(tokens)
        return any(c > 1 for tok, c in counts.items() if len(tok) > 2)
    return series.map(_check)


# ------------------------------------------------------------
# ADDRESS-SPECIFIC DERIVED FIELDS
# ------------------------------------------------------------

def extract_unit(series: pd.Series) -> pd.Series:
    return series.map(
        lambda x: (m.group(1) if (m := UNIT_PATTERN.search(x)) else np.nan)
        if pd.notna(x) else np.nan
    )


def remove_unit_fragment(series: pd.Series) -> pd.Series:
    return series.str.replace(UNIT_PATTERN, " ", regex=True).pipe(normalize_whitespace)


def extract_numeric_tokens(series: pd.Series) -> pd.Series:
    return series.map(lambda x: _NUMERIC_TOKEN_RE.findall(x) if pd.notna(x) and x else [])


# ------------------------------------------------------------
# MAIN PER-SOURCE PREPROCESSING FUNCTION
# ------------------------------------------------------------

def preprocess_source(df: pd.DataFrame, id_col: str = "entity_id") -> pd.DataFrame:
    out = df.copy()

    # --- missing flags first, on raw columns ---
    raw_name = out["business_name"]
    raw_addr = out["business_address"]
    out["name_is_missing"] = raw_name.isna() | (raw_name.astype(str).str.strip() == "")
    out["address_is_missing"] = raw_addr.isna() | (raw_addr.astype(str).str.strip() == "")

    name_raw_filled = raw_name.fillna("")
    addr_raw_filled = raw_addr.fillna("")

    # --- structured extraction on RAW fields (before normalization) ---
    out["domain"] = extract_domain_series(name_raw_filled)
    out["has_repeated_token"] = has_repeated_token(name_raw_filled)
    out["address_numeric_tokens"] = extract_numeric_tokens(addr_raw_filled)

    # --- script detection on RAW fields, before any normalization ---
    out["script_name"] = detect_script_series(raw_name)
    out["script_address"] = detect_script_series(raw_addr)

    # --- domain fragment removal so it never pollutes name_normalized ---
    name_no_domain = remove_domain_fragment(name_raw_filled)

    # --- NAME pipeline ---
    name_clean = basic_clean(name_no_domain)
    name_clean = name_clean.str.replace(r"#\w*", " ", regex=True).pipe(normalize_whitespace)
    out["name_normalized"] = apply_dictionary(name_clean, SUFFIX_MAP)
    out["name_suffix_stripped"] = strip_suffixes(out["name_normalized"])
    out["name_sorted_tokens"] = sorted_tokens(out["name_suffix_stripped"])
    out["name_transliterated"] = transliterate_series(out["name_normalized"], out["script_name"])
    out["name_transliterated_suffix_stripped"] = strip_suffixes(out["name_transliterated"])
    out["name_phonetic"] = phonetic_code(out["name_transliterated"])

    out.loc[out["name_is_missing"], [
        "name_normalized", "name_suffix_stripped", "name_sorted_tokens",
        "name_transliterated", "name_transliterated_suffix_stripped", "name_phonetic",
    ]] = np.nan

    # --- ADDRESS pipeline ---
    addr_clean = basic_clean(addr_raw_filled)
    addr_clean = apply_dictionary(addr_clean, STREET_MAP)
    out["unit_value"] = extract_unit(addr_clean)
    addr_no_unit = remove_unit_fragment(addr_clean)
    out["address_normalized"] = addr_no_unit.str.replace(r"#\w*", " ", regex=True).pipe(normalize_whitespace)
    out["address_transliterated"] = transliterate_series(out["address_normalized"], out["script_address"])

    out.loc[out["address_is_missing"], [
        "unit_value", "address_normalized", "address_transliterated",
    ]] = np.nan
    out.loc[out["address_is_missing"], "address_numeric_tokens"] = pd.Series(
        [[] for _ in range(out["address_is_missing"].sum())],
        index=out.index[out["address_is_missing"]],
    )

    # --- COUNTRY: light touch only ---
    out["country_normalized"] = out["country"].astype(str).str.strip().str.casefold()

    final_cols = [
        id_col, "business_name", "business_address", "country",
        "name_is_missing", "address_is_missing",
        "script_name", "script_address",
        "name_normalized", "name_suffix_stripped", "name_sorted_tokens",
        "name_transliterated", "name_transliterated_suffix_stripped", "name_phonetic",
        "address_normalized", "address_transliterated",
        "address_numeric_tokens", "unit_value",
        "domain", "has_repeated_token", "country_normalized",
    ]
    final_cols = [c for c in final_cols if c in out.columns]
    return out[final_cols]

df2_5k = df2.head(5000).copy()

print("Preprocessing the first 5,000 rows of df2 using the defined pipeline:")
processed_df2_5k = preprocess_source(df2_5k)

print("Displaying a sample of the processed first 5,000 rows of df2:")
pd.set_option("display.max_colwidth", 60)
display(processed_df2_5k[[
    "entity_id",
    "domain",
    "script_name",
    "name_normalized",
    "name_transliterated",
    "name_phonetic",
    "script_address",
    "address_normalized",
    "address_transliterated",
    "address_numeric_tokens",
    "has_repeated_token",
]].head())

output_path = '/content/drive/MyDrive/Amazon ML Challenge/processed_df2_5k.tsv'
processed_df2_5k.to_csv(output_path, sep='\t', index=False)
print(f"Processed df2_5k saved to: {output_path}")
